// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/screening.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// screening_model_1_predictions
Rcpp::DataFrame screening_model_1_predictions(std::vector<double> t, std::vector<double> ti, double shape1, double scale1, double shape2, double scale2, double beta, bool simple, double tol);
RcppExport SEXP _screening_screening_model_1_predictions(SEXP tSEXP, SEXP tiSEXP, SEXP shape1SEXP, SEXP scale1SEXP, SEXP shape2SEXP, SEXP scale2SEXP, SEXP betaSEXP, SEXP simpleSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type t(tSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< double >::type shape1(shape1SEXP);
    Rcpp::traits::input_parameter< double >::type scale1(scale1SEXP);
    Rcpp::traits::input_parameter< double >::type shape2(shape2SEXP);
    Rcpp::traits::input_parameter< double >::type scale2(scale2SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< bool >::type simple(simpleSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_1_predictions(t, ti, shape1, scale1, shape2, scale2, beta, simple, tol));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_1_likes
std::vector<double> screening_model_1_likes(Rcpp::List inputs, double shape1, double scale1, double shape2, double scale2, double beta, double tol);
RcppExport SEXP _screening_screening_model_1_likes(SEXP inputsSEXP, SEXP shape1SEXP, SEXP scale1SEXP, SEXP shape2SEXP, SEXP scale2SEXP, SEXP betaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type shape1(shape1SEXP);
    Rcpp::traits::input_parameter< double >::type scale1(scale1SEXP);
    Rcpp::traits::input_parameter< double >::type shape2(shape2SEXP);
    Rcpp::traits::input_parameter< double >::type scale2(scale2SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_1_likes(inputs, shape1, scale1, shape2, scale2, beta, tol));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_2_predictions
Rcpp::DataFrame screening_model_2_predictions(std::vector<double> t, std::vector<double> ti, std::vector<double> yi, double shape1, double scale1, double shape2, double scale2, double beta0, double beta1, bool simple, double tol);
RcppExport SEXP _screening_screening_model_2_predictions(SEXP tSEXP, SEXP tiSEXP, SEXP yiSEXP, SEXP shape1SEXP, SEXP scale1SEXP, SEXP shape2SEXP, SEXP scale2SEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP simpleSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type t(tSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type shape1(shape1SEXP);
    Rcpp::traits::input_parameter< double >::type scale1(scale1SEXP);
    Rcpp::traits::input_parameter< double >::type shape2(shape2SEXP);
    Rcpp::traits::input_parameter< double >::type scale2(scale2SEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< bool >::type simple(simpleSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_2_predictions(t, ti, yi, shape1, scale1, shape2, scale2, beta0, beta1, simple, tol));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_2_likes
std::vector<double> screening_model_2_likes(Rcpp::List inputs, double shape1, double scale1, double shape2, double scale2, double beta0, double beta1, double tol);
RcppExport SEXP _screening_screening_model_2_likes(SEXP inputsSEXP, SEXP shape1SEXP, SEXP scale1SEXP, SEXP shape2SEXP, SEXP scale2SEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type shape1(shape1SEXP);
    Rcpp::traits::input_parameter< double >::type scale1(scale1SEXP);
    Rcpp::traits::input_parameter< double >::type shape2(shape2SEXP);
    Rcpp::traits::input_parameter< double >::type scale2(scale2SEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_2_likes(inputs, shape1, scale1, shape2, scale2, beta0, beta1, tol));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_3_predictions
Rcpp::DataFrame screening_model_3_predictions(std::vector<double> t, std::vector<double> ti, std::vector<double> yi, std::vector<int> bxi, double shape1, double scale1, double shape2, double scale2, double beta0, double beta1, double PrFalseNegBx, bool simple, double tol);
RcppExport SEXP _screening_screening_model_3_predictions(SEXP tSEXP, SEXP tiSEXP, SEXP yiSEXP, SEXP bxiSEXP, SEXP shape1SEXP, SEXP scale1SEXP, SEXP shape2SEXP, SEXP scale2SEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP PrFalseNegBxSEXP, SEXP simpleSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type t(tSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type bxi(bxiSEXP);
    Rcpp::traits::input_parameter< double >::type shape1(shape1SEXP);
    Rcpp::traits::input_parameter< double >::type scale1(scale1SEXP);
    Rcpp::traits::input_parameter< double >::type shape2(shape2SEXP);
    Rcpp::traits::input_parameter< double >::type scale2(scale2SEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type PrFalseNegBx(PrFalseNegBxSEXP);
    Rcpp::traits::input_parameter< bool >::type simple(simpleSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_3_predictions(t, ti, yi, bxi, shape1, scale1, shape2, scale2, beta0, beta1, PrFalseNegBx, simple, tol));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_3_likes
std::vector<double> screening_model_3_likes(Rcpp::List inputs, double shape1, double scale1, double shape2, double scale2, double beta0, double beta1, double PrFalseNegBx, double tol, std::string return_type, Rcpp::Nullable<Rcpp::NumericVector> weights);
RcppExport SEXP _screening_screening_model_3_likes(SEXP inputsSEXP, SEXP shape1SEXP, SEXP scale1SEXP, SEXP shape2SEXP, SEXP scale2SEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP PrFalseNegBxSEXP, SEXP tolSEXP, SEXP return_typeSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type shape1(shape1SEXP);
    Rcpp::traits::input_parameter< double >::type scale1(scale1SEXP);
    Rcpp::traits::input_parameter< double >::type shape2(shape2SEXP);
    Rcpp::traits::input_parameter< double >::type scale2(scale2SEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type PrFalseNegBx(PrFalseNegBxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type return_type(return_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_3_likes(inputs, shape1, scale1, shape2, scale2, beta0, beta1, PrFalseNegBx, tol, return_type, weights));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_3_likes_MVK
std::vector<double> screening_model_3_likes_MVK(Rcpp::List inputs, double A, double B, double delta, double shape2, double scale2, double beta0, double beta1, double PrFalseNegBx, double tol, std::string return_type, Rcpp::Nullable<Rcpp::NumericVector> weights, bool left_trunc, Rcpp::Nullable<Rcpp::DataFrame> incidence);
RcppExport SEXP _screening_screening_model_3_likes_MVK(SEXP inputsSEXP, SEXP ASEXP, SEXP BSEXP, SEXP deltaSEXP, SEXP shape2SEXP, SEXP scale2SEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP PrFalseNegBxSEXP, SEXP tolSEXP, SEXP return_typeSEXP, SEXP weightsSEXP, SEXP left_truncSEXP, SEXP incidenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type shape2(shape2SEXP);
    Rcpp::traits::input_parameter< double >::type scale2(scale2SEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type PrFalseNegBx(PrFalseNegBxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type return_type(return_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type left_trunc(left_truncSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::DataFrame> >::type incidence(incidenceSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_3_likes_MVK(inputs, A, B, delta, shape2, scale2, beta0, beta1, PrFalseNegBx, tol, return_type, weights, left_trunc, incidence));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_3_likes_MVK_lognorm
std::vector<double> screening_model_3_likes_MVK_lognorm(Rcpp::List inputs, double A, double B, double delta, double mulog, double sdlog, double beta0, double beta1, double PrFalseNegBx, double tol, std::string return_type, Rcpp::Nullable<Rcpp::NumericVector> weights, bool left_trunc, Rcpp::Nullable<Rcpp::DataFrame> incidence);
RcppExport SEXP _screening_screening_model_3_likes_MVK_lognorm(SEXP inputsSEXP, SEXP ASEXP, SEXP BSEXP, SEXP deltaSEXP, SEXP mulogSEXP, SEXP sdlogSEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP PrFalseNegBxSEXP, SEXP tolSEXP, SEXP return_typeSEXP, SEXP weightsSEXP, SEXP left_truncSEXP, SEXP incidenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type mulog(mulogSEXP);
    Rcpp::traits::input_parameter< double >::type sdlog(sdlogSEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type PrFalseNegBx(PrFalseNegBxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type return_type(return_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type left_trunc(left_truncSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::DataFrame> >::type incidence(incidenceSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_3_likes_MVK_lognorm(inputs, A, B, delta, mulog, sdlog, beta0, beta1, PrFalseNegBx, tol, return_type, weights, left_trunc, incidence));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_3_likes_MVK_exp
std::vector<double> screening_model_3_likes_MVK_exp(Rcpp::List inputs, double A, double B, double delta, double rate, double beta0, double beta1, double PrFalseNegBx, double tol, std::string return_type, Rcpp::Nullable<Rcpp::NumericVector> weights, bool left_trunc, Rcpp::Nullable<Rcpp::DataFrame> incidence);
RcppExport SEXP _screening_screening_model_3_likes_MVK_exp(SEXP inputsSEXP, SEXP ASEXP, SEXP BSEXP, SEXP deltaSEXP, SEXP rateSEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP PrFalseNegBxSEXP, SEXP tolSEXP, SEXP return_typeSEXP, SEXP weightsSEXP, SEXP left_truncSEXP, SEXP incidenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type PrFalseNegBx(PrFalseNegBxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type return_type(return_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type left_trunc(left_truncSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::DataFrame> >::type incidence(incidenceSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_3_likes_MVK_exp(inputs, A, B, delta, rate, beta0, beta1, PrFalseNegBx, tol, return_type, weights, left_trunc, incidence));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_2_likes_MVK_exp
std::vector<double> screening_model_2_likes_MVK_exp(Rcpp::List inputs, double A, double B, double delta, double rate, double beta0, double beta1, double tol);
RcppExport SEXP _screening_screening_model_2_likes_MVK_exp(SEXP inputsSEXP, SEXP ASEXP, SEXP BSEXP, SEXP deltaSEXP, SEXP rateSEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_2_likes_MVK_exp(inputs, A, B, delta, rate, beta0, beta1, tol));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_1_likes_MVK_exp
std::vector<double> screening_model_1_likes_MVK_exp(Rcpp::List inputs, double A, double B, double delta, double rate, double beta, double tol);
RcppExport SEXP _screening_screening_model_1_likes_MVK_exp(SEXP inputsSEXP, SEXP ASEXP, SEXP BSEXP, SEXP deltaSEXP, SEXP rateSEXP, SEXP betaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_1_likes_MVK_exp(inputs, A, B, delta, rate, beta, tol));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_4_likes_loglin
std::vector<double> screening_model_4_likes_loglin(Rcpp::List inputs, double A, double B, double delta, double rate, double beta0, double beta1, double b0_psa, double b1_psa, double b2_psa, double sigma_psa, double PrFalseNegBx, double tol, std::string return_type, Rcpp::Nullable<Rcpp::NumericVector> weights, bool left_trunc, Rcpp::Nullable<Rcpp::DataFrame> incidence);
RcppExport SEXP _screening_screening_model_4_likes_loglin(SEXP inputsSEXP, SEXP ASEXP, SEXP BSEXP, SEXP deltaSEXP, SEXP rateSEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP b0_psaSEXP, SEXP b1_psaSEXP, SEXP b2_psaSEXP, SEXP sigma_psaSEXP, SEXP PrFalseNegBxSEXP, SEXP tolSEXP, SEXP return_typeSEXP, SEXP weightsSEXP, SEXP left_truncSEXP, SEXP incidenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type b0_psa(b0_psaSEXP);
    Rcpp::traits::input_parameter< double >::type b1_psa(b1_psaSEXP);
    Rcpp::traits::input_parameter< double >::type b2_psa(b2_psaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_psa(sigma_psaSEXP);
    Rcpp::traits::input_parameter< double >::type PrFalseNegBx(PrFalseNegBxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type return_type(return_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type left_trunc(left_truncSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::DataFrame> >::type incidence(incidenceSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_4_likes_loglin(inputs, A, B, delta, rate, beta0, beta1, b0_psa, b1_psa, b2_psa, sigma_psa, PrFalseNegBx, tol, return_type, weights, left_trunc, incidence));
    return rcpp_result_gen;
END_RCPP
}
// screening_model_1_likes_MVK_exp_grad
Rcpp::List screening_model_1_likes_MVK_exp_grad(Rcpp::List inputs, double A, double B, double delta, double rate, double beta, double tol, int n_threads);
RcppExport SEXP _screening_screening_model_1_likes_MVK_exp_grad(SEXP inputsSEXP, SEXP ASEXP, SEXP BSEXP, SEXP deltaSEXP, SEXP rateSEXP, SEXP betaSEXP, SEXP tolSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(screening_model_1_likes_MVK_exp_grad(inputs, A, B, delta, rate, beta, tol, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_screening_screening_model_1_predictions", (DL_FUNC) &_screening_screening_model_1_predictions, 9},
    {"_screening_screening_model_1_likes", (DL_FUNC) &_screening_screening_model_1_likes, 7},
    {"_screening_screening_model_2_predictions", (DL_FUNC) &_screening_screening_model_2_predictions, 11},
    {"_screening_screening_model_2_likes", (DL_FUNC) &_screening_screening_model_2_likes, 8},
    {"_screening_screening_model_3_predictions", (DL_FUNC) &_screening_screening_model_3_predictions, 13},
    {"_screening_screening_model_3_likes", (DL_FUNC) &_screening_screening_model_3_likes, 11},
    {"_screening_screening_model_3_likes_MVK", (DL_FUNC) &_screening_screening_model_3_likes_MVK, 14},
    {"_screening_screening_model_3_likes_MVK_lognorm", (DL_FUNC) &_screening_screening_model_3_likes_MVK_lognorm, 14},
    {"_screening_screening_model_3_likes_MVK_exp", (DL_FUNC) &_screening_screening_model_3_likes_MVK_exp, 13},
    {"_screening_screening_model_2_likes_MVK_exp", (DL_FUNC) &_screening_screening_model_2_likes_MVK_exp, 8},
    {"_screening_screening_model_1_likes_MVK_exp", (DL_FUNC) &_screening_screening_model_1_likes_MVK_exp, 7},
    {"_screening_screening_model_4_likes_loglin", (DL_FUNC) &_screening_screening_model_4_likes_loglin, 17},
    {"_screening_screening_model_1_likes_MVK_exp_grad", (DL_FUNC) &_screening_screening_model_1_likes_MVK_exp_grad, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_screening(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
