# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
screening_model_likes <- function(model, inputs, onset_pars, sojourn_pars, biom_pars, grads = FALSE, tol = 1e-6, return_type = "", weights = NULL, left_trunc = FALSE, incidence = NULL, n_threads = 0L) {
    .Call('_screening_screening_model_likes', PACKAGE = 'screening', model, inputs, onset_pars, sojourn_pars, biom_pars, grads, tol, return_type, weights, left_trunc, incidence, n_threads)
}

