# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Do predictions for ScreeningModel1
#' @name ScreeningModel1
#' @param t double vector of times to evaluate
#' @param ti double vector of screening times
#' @param scale1 Weibull scale for onset
#' @param shape1 Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta false negative fraction for screening
#' @param simple whether to calculate Z using a simple method (complement) or integration (defaults to true)
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return data-frame with elements t, X, Y, Z (for state probabilities) and I (for incidence)
#' @importFrom Rcpp sourceCpp
#' @examples
#' par(mfrow=1:2)
#' x=seq(0,30,length=301)
#' screening_model_1_predictions(t=x, tj=vector("double"), shape1=1.5, shape2=1.5, scale1=20, scale2=10, beta=0.4) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="No screening"))
#' screening_model_1_predictions(t=x, tj=c(10,15, 20, 25), shape1=1.5, shape2=1.5, scale1=20, scale2=10, beta=0.4) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="Screening"))
#' @export
screening_model_1_predictions <- function(t, ti, shape1 = 1, scale1 = 1, shape2 = 1, scale2 = 1, beta = 0.05, simple = TRUE, tol = 1e-6) {
    .Call('_screening_screening_model_1_predictions', PACKAGE = 'screening', t, ti, shape1, scale1, shape2, scale2, beta, simple, tol)
}

#' Do likelihood calculations for ScreeningModel1
#' @name ScreeningModel1
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param scale1 Weibull scale for onset
#' @param shape1 Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta false negative fraction for screening
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return vector of likelihoods
#' @export
screening_model_1_likes <- function(inputs, shape1 = 1.0, scale1 = 1.0, shape2 = 1.0, scale2 = 1.0, beta = 0.05, tol = 1e-6) {
    .Call('_screening_screening_model_1_likes', PACKAGE = 'screening', inputs, shape1, scale1, shape2, scale2, beta, tol)
}

#' Do predictions for ScreeningModel2
#' @name ScreeningModel2
#' @param t double vector of times to evaluate
#' @param ti double vector of screening times
#' @param yi double vector of screening times
#' @param scale1 Weibull scale for onset
#' @param shape1 Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param simple whether to calculate Z using a simple method (complement) or integration (defaults to true)
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return data-frame with elements t, X, Y, Z (for state probabilities) and I (for incidence)
#' @importFrom Rcpp sourceCpp
#' @examples
#' par(mfrow=1:2)
#' x=seq(0,30,length=301)
#' screening_model_2_predictions(t=x, ti=vector("double"), yi=vector("double"), shape1=1.5, shape2=1.5, scale1=20, scale2=10) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="No screening"))
#' screening_model_2_predictions(t=x, ti=c(10,15, 20, 25), yi=c(3,3,3), shape1=1.5, shape2=1.5, scale1=20, scale2=10) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="Screening"))
#' @export
screening_model_2_predictions <- function(t, ti, yi, shape1 = 1, scale1 = 1, shape2 = 1, scale2 = 1, beta0 = -3.0, beta1 = 1.0, simple = TRUE, tol = 1e-6) {
    .Call('_screening_screening_model_2_predictions', PACKAGE = 'screening', t, ti, yi, shape1, scale1, shape2, scale2, beta0, beta1, simple, tol)
}

#' Do likelihood calculations for ScreeningModel2
#' @name ScreeningModel2
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param scale1 Weibull scale for onset
#' @param shape1 Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return vector of likelihoods
#' @export
screening_model_2_likes <- function(inputs, shape1 = 1.0, scale1 = 1.0, shape2 = 1.0, scale2 = 1.0, beta0 = -3.0, beta1 = 1.0, tol = 1e-6) {
    .Call('_screening_screening_model_2_likes', PACKAGE = 'screening', inputs, shape1, scale1, shape2, scale2, beta0, beta1, tol)
}

#' Do predictions for ScreeningModel3
#' @name ScreeningModel3
#' @param t double vector of times to evaluate
#' @param ti double vector of screening times
#' @param yi double vector of screening times
#' @param bxi integer vector of biopsy choices
#' @param scale1 Weibull scale for onset
#' @param shape1 Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param PrFalseNegBx probability of a false negative biopsy | cancer, biopsy undertaken
#' @param simple whether to calculate Z using a simple method (complement) or integration (defaults to true)
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return data-frame with elements t, X, Y, Z (for state probabilities) and I (for incidence)
#' @importFrom Rcpp sourceCpp
#' @examples
#' par(mfrow=1:2)
#' x=seq(0,30,length=301)
#' screening_model_3_predictions(t=x, ti=vector("double"), yi=vector("double"), bxi=vector("integer"), shape1=1.5, shape2=1.5, scale1=20, scale2=10) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="No screening"))
#' screening_model_3_predictions(t=x, ti=c(10,15, 20, 25), yi=c(3,3,3), bxi=c(FALSE,FALSE,TRUE), shape1=1.5, shape2=1.5, scale1=20, scale2=10) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="Screening"))
#' @export
screening_model_3_predictions <- function(t, ti, yi, bxi, shape1 = 1, scale1 = 1, shape2 = 1, scale2 = 1, beta0 = -3.0, beta1 = 1.0, PrFalseNegBx = 0.05, simple = TRUE, tol = 1e-6) {
    .Call('_screening_screening_model_3_predictions', PACKAGE = 'screening', t, ti, yi, bxi, shape1, scale1, shape2, scale2, beta0, beta1, PrFalseNegBx, simple, tol)
}

#' Do likelihood calculations for ScreeningModel3
#' @name ScreeningModel3
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param scale1 Weibull scale for onset
#' @param shape1 Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param PrFalseNegBx probability of a false negative biopsy | cancer, biopsy undertaken
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @param return_type string, if "weighted_ll" returns sum of weighted log-likelihoods (default "")
#' @param weights vector of weights corresponding to inputs, required if return_type is "weighted_ll"
#' @return vector of likelihoods (or vector of length 1 containing weighted log-likelihood sum)
#' @export
screening_model_3_likes <- function(inputs, shape1 = 1.0, scale1 = 1.0, shape2 = 1.0, scale2 = 1.0, beta0 = -3.0, beta1 = 1.0, PrFalseNegBx = 0.05, tol = 1e-6, return_type = "", weights = NULL) {
    .Call('_screening_screening_model_3_likes', PACKAGE = 'screening', inputs, shape1, scale1, shape2, scale2, beta0, beta1, PrFalseNegBx, tol, return_type, weights)
}

#' Do likelihood calculations for ScreeningModel3 using MVK onset
#' @name ScreeningModel3MVK
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param A MVK parameter A (typically negative, related to net proliferation)
#' @param B MVK parameter B (typically positive, related to malignant transformation)
#' @param delta MVK parameter delta (ratio of initiation rate to cell division rate)
#' @param shape2 Weibull shape for clinical diagnosis (Sojourn density)
#' @param scale2 Weibull scale for clinical diagnosis (Sojourn density)
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param PrFalseNegBx probability of a false negative biopsy | cancer, biopsy undertaken
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @param return_type string, if "weighted_ll" returns sum of weighted log-likelihoods (default "")
#' @param weights vector of weights corresponding to inputs, required if return_type is "weighted_ll"
#' @param left_trunc bool, apply left truncation adjustment (default false)
#' @param incidence DataFrame containing background incidence rates, required if left_trunc is true
#' @return vector of likelihoods (or vector of length 1 containing weighted log-likelihood sum)
#' @export
screening_model_3_likes_MVK <- function(inputs, A = -0.1, B = 1e-4, delta = 1e-4, shape2 = 1, scale2 = 1, beta0 = -3.0, beta1 = 1.0, PrFalseNegBx = 0.05, tol = 1e-6, return_type = "", weights = NULL, left_trunc = FALSE, incidence = NULL) {
    .Call('_screening_screening_model_3_likes_MVK', PACKAGE = 'screening', inputs, A, B, delta, shape2, scale2, beta0, beta1, PrFalseNegBx, tol, return_type, weights, left_trunc, incidence)
}

#' Do likelihood calculations for ScreeningModel3 using MVK onset and Lognormal Sojourn
#' @name ScreeningModel3MVKLognorm
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param A MVK parameter A (typically negative, related to net proliferation)
#' @param B MVK parameter B (typically positive, related to malignant transformation)
#' @param delta MVK parameter delta (ratio of initiation rate to cell division rate)
#' @param mulog Lognormal meanlog for clinical diagnosis (Sojourn density, default=2.3 ~ 10 yrs)
#' @param sdlog Lognormal sdlog for clinical diagnosis (Sojourn density, default=0.6)
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param PrFalseNegBx probability of a false negative biopsy | cancer, biopsy undertaken
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @param return_type string, if "weighted_ll" returns sum of weighted log-likelihoods (default "")
#' @param weights vector of weights corresponding to inputs, required if return_type is "weighted_ll"
#' @param left_trunc bool, apply left truncation adjustment (default false)
#' @param incidence DataFrame containing background incidence rates, required if left_trunc is true
#' @return vector of likelihoods (or vector of length 1 containing weighted log-likelihood sum)
#' @export
screening_model_3_likes_MVK_lognorm <- function(inputs, A = -0.1, B = 1e-4, delta = 1e-4, mulog = 2.3, sdlog = 0.6, beta0 = -3.0, beta1 = 1.0, PrFalseNegBx = 0.05, tol = 1e-6, return_type = "", weights = NULL, left_trunc = FALSE, incidence = NULL) {
    .Call('_screening_screening_model_3_likes_MVK_lognorm', PACKAGE = 'screening', inputs, A, B, delta, mulog, sdlog, beta0, beta1, PrFalseNegBx, tol, return_type, weights, left_trunc, incidence)
}

#' Do likelihood calculations for ScreeningModel3 using MVK onset and Exponential Sojourn
#' @name ScreeningModel3MVKExp
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param A MVK parameter A (typically negative, related to net proliferation)
#' @param B MVK parameter B (typically positive, related to malignant transformation)
#' @param delta MVK parameter delta (ratio of initiation rate to cell division rate)
#' @param rate Exponential rate for clinical diagnosis (Sojourn density, default=0.1 ~ mean 10 yrs)
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param PrFalseNegBx probability of a false negative biopsy | cancer, biopsy undertaken
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @param return_type string, if "weighted_ll" returns sum of weighted log-likelihoods (default "")
#' @param weights vector of weights corresponding to inputs, required if return_type is "weighted_ll"
#' @param left_trunc bool, apply left truncation adjustment (default false)
#' @param incidence DataFrame containing background incidence rates, required if left_trunc is true
#' @return vector of likelihoods (or vector of length 1 containing weighted log-likelihood sum)
#' @export
screening_model_3_likes_MVK_exp <- function(inputs, A = -0.1, B = 1e-4, delta = 1e-4, rate = 0.1, beta0 = -3.0, beta1 = 1.0, PrFalseNegBx = 0.05, tol = 1e-6, return_type = "", weights = NULL, left_trunc = FALSE, incidence = NULL) {
    .Call('_screening_screening_model_3_likes_MVK_exp', PACKAGE = 'screening', inputs, A, B, delta, rate, beta0, beta1, PrFalseNegBx, tol, return_type, weights, left_trunc, incidence)
}

#' Do likelihood calculations for ScreeningModel2 using MVK onset and Exponential Sojourn
#' @name ScreeningModel2MVKExp
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param A MVK parameter A (typically negative, related to net proliferation)
#' @param B MVK parameter B (typically positive, related to malignant transformation)
#' @param delta MVK parameter delta (ratio of initiation rate to cell division rate)
#' @param rate Exponential rate for clinical diagnosis (Sojourn density, default=0.1 ~ mean 10 yrs)
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return vector of likelihoods
#' @export
screening_model_2_likes_MVK_exp <- function(inputs, A = -0.1, B = 1e-4, delta = 1e-4, rate = 0.1, beta0 = -3.0, beta1 = 1.0, tol = 1e-6) {
    .Call('_screening_screening_model_2_likes_MVK_exp', PACKAGE = 'screening', inputs, A, B, delta, rate, beta0, beta1, tol)
}

#' Do likelihood calculations for ScreeningModel1 using MVK onset and Exponential Sojourn
#' @name ScreeningModel1MVKExp
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param A MVK parameter A (typically negative, related to net proliferation)
#' @param B MVK parameter B (typically positive, related to malignant transformation)
#' @param delta MVK parameter delta (ratio of initiation rate to cell division rate)
#' @param rate Exponential rate for clinical diagnosis (Sojourn density, default=0.1 ~ mean 10 yrs)
#' @param beta false negative fraction for screening
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return vector of likelihoods
#' @export
screening_model_1_likes_MVK_exp <- function(inputs, A = -0.1, B = 1e-4, delta = 1e-4, rate = 0.1, beta = 0.05, tol = 1e-6) {
    .Call('_screening_screening_model_1_likes_MVK_exp', PACKAGE = 'screening', inputs, A, B, delta, rate, beta, tol)
}

#' Do likelihood calculations for ScreeningModel4 using MVK onset, Exponential Sojourn, and Log-linear PSA with change of slope for onset
#' @name ScreeningModel4LikesLoglin
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times, yi for biomarker values, bxi for biopsy indicators, and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param A MVK parameter A (typically negative, related to net proliferation)
#' @param B MVK parameter B (typically positive, related to malignant transformation)
#' @param delta MVK parameter delta (ratio of initiation rate to cell division rate)
#' @param rate Exponential rate for clinical diagnosis (Sojourn density, default=0.1 ~ mean 10 yrs)
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param b0_psa intercept for log-linear PSA model
#' @param b1_psa slope for age for log-linear PSA model
#' @param b2_psa slope increment after onset for log-linear PSA model
#' @param sigma_psa standard deviation of log(PSA)
#' @param PrFalseNegBx probability of a false negative biopsy | cancer, biopsy undertaken
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @param return_type string, if "weighted_ll" returns sum of weighted log-likelihoods (default "")
#' @param weights vector of weights corresponding to inputs, required if return_type is "weighted_ll"
#' @param left_trunc bool, apply left truncation adjustment (default false)
#' @param incidence DataFrame containing background incidence rates, required if left_trunc is true
#' @return vector of likelihoods (or vector of length 1 containing weighted log-likelihood sum)
#' @export
screening_model_4_likes_loglin <- function(inputs, A = -0.1, B = 1e-4, delta = 1e-4, rate = 0.1, beta0 = 3.2892, beta1 = -0.5533, b0_psa = -1.6094, b1_psa = 0.0200, b2_psa = 0.1094, sigma_psa = 0.2879, PrFalseNegBx = 0.0, tol = 1e-6, return_type = "", weights = NULL, left_trunc = FALSE, incidence = NULL) {
    .Call('_screening_screening_model_4_likes_loglin', PACKAGE = 'screening', inputs, A, B, delta, rate, beta0, beta1, b0_psa, b1_psa, b2_psa, sigma_psa, PrFalseNegBx, tol, return_type, weights, left_trunc, incidence)
}

#' Do AD likelihood and gradient calculations for ScreeningModel1 (MVK + Exp)
#' @name screening_model_1_likes_MVK_exp_grad
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param A MVK parameter A (active for AD)
#' @param B MVK parameter B (active for AD)
#' @param delta MVK parameter delta (active for AD)
#' @param rate Exponential rate for clinical diagnosis (active for AD)
#' @param beta false negative fraction for screening (active for AD)
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @param n_threads number of threads to use (default=0, auto-detects)
#' @return list containing likelihoods and gradients
#' @export
screening_model_1_likes_MVK_exp_grad <- function(inputs, A = -0.1, B = 1e-4, delta = 1e-4, rate = 0.1, beta = 0.05, tol = 1e-6, n_threads = 0L) {
    .Call('_screening_screening_model_1_likes_MVK_exp_grad', PACKAGE = 'screening', inputs, A, B, delta, rate, beta, tol, n_threads)
}

