# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' State probability predictions for a screening model
NULL

#' Compute Likelihoods for Screening Models
#'
#' @name screening_model_likes
#' @param model integer; one of 1..5
#' @param inputs list; per-subject screening histories
#' @param onset_pars list; onset distribution parameters
#' @param sojourn_pars list; sojourn distribution parameters
#' @param biom_pars list; biomarker / test parameters
#' @param grads logical; if TRUE return AD gradients
#' @param tol numeric; integration tolerance
#' @param return_type character; "" for raw likelihoods, "weighted_ll" for weighted log-likelihood
#' @param weights numeric vector or NULL
#' @param left_trunc logical; if TRUE apply left-truncation correction
#' @param lt_date numeric; truncation date as days since 1970-01-01
#' @param n_threads integer; OpenMP threads (0 = all available)
#' @return A list with elements `likelihoods` and (if grads) `gradients`.
#' @export
screening_model_likes <- function(model, inputs, onset_pars, sojourn_pars, biom_pars, grads = FALSE, tol = 1e-6, return_type = "", weights = NULL, left_trunc = FALSE, lt_date = 0.0, n_threads = 0L) {
    .Call('_screening_screening_model_likes', PACKAGE = 'screening', model, inputs, onset_pars, sojourn_pars, biom_pars, grads, tol, return_type, weights, left_trunc, lt_date, n_threads)
}

screening_model_predictions <- function(model, t, history, onset_pars, sojourn_pars, biom_pars, simple = TRUE, tol = 1e-6) {
    .Call('_screening_screening_model_predictions', PACKAGE = 'screening', model, t, history, onset_pars, sojourn_pars, biom_pars, simple, tol)
}

